### PR TITLE
GH-87: [Vector] Add ExtensionWriter

### LINKED ISSUE #87: [Java] StructVector throws with ExtensionType
### Describe the bug, including details regarding any error messages, version, and platform.

Currently when creating a struct vector with a child being an extension type things throw:
```java
  @Test
  public void testStructVectorWithExtensionTypes() {
    TestExtensionType.UuidType uuidType = new TestExtensionType.UuidType();
    Field uuidField =  new Field("struct_child", FieldType.nullable(uuidType), null);
    Field structField = new Field("struct", FieldType.nullable(new ArrowType.Struct()), List.of(uuidField));
    // throws
    StructVector s1 = new StructVector(structField, allocator, null);
    // doesn't throw
    StructVector s2 = (StructVector) structField.createVector(allocator);
    s1.close();
    s2.close();
  }
```

I am mainly running into this while trying to create a `TransferPair`.
```java
  @Test
  public void testStructVectorTransferPairWithExtensionType() {
    TestExtensionType.UuidType uuidType = new TestExtensionType.UuidType();
    Field uuidField =  new Field("uuid_child", FieldType.nullable(uuidType), null);
    Field structField = new Field("struct", FieldType.nullable(new ArrowType.Struct()), List.of(uuidField));

    StructVector s1 = (StructVector) structField.createVector(allocator);
    TestExtensionType.UuidVector uuidVector = s1.addOrGet("uuid_child", FieldType.nullable(uuidType), TestExtensionType.UuidVector.class);
    s1.setValueCount(1);
    uuidVector.set(0, new UUID(1, 2));
    s1.setIndexDefined(0);

    TransferPair tp = s1.getTransferPair(structField, allocator);
    final StructVector toVector = (StructVector) tp.getTo();
    assertEquals(s1.getField(), toVector.getField());
    assertEquals(s1.getField().getChildren().get(0), toVector.getField().getChildren().get(0));
    // also fails but probably another issue
//    assertEquals(s1.getValueCount(), toVector.getValueCount());
//    assertEquals(s1, toVector);

    s1.close();
    toVector.close();
  }
```

### Component(s)

Java

### PR DESCRIPTION
**Pull request by xxlaykxx**
Based on changes from https://github.com/apache/arrow/pull/41731.

## What's Changed

Added writer ExtensionWriter with 3 methods:
- write method  for writing values from Extension holders;
- writeExtensionType method for writing values (arguments is Object because we don't know exact type);
- addExtensionTypeFactory method - because the exact vector and value type are unknown, the user should create their own extension type vector, write for it, and ExtensionTypeFactory, which should map the vector and writer.

Closes #87.

Co-authored-by: Finn Völkel <finn.volkel@gmail.com>

### CODE REVIEW

**Comment by xxlaykxx** [comment]
@lidavidm, please take a look if this approach can be used

File: vector/src/main/java/org/apache/arrow/vector/complex/impl/ExtensionTypeWriterFactory.java [hunk 1]
```diff
@@ -0,0 +1,23 @@
...
+ * distributed under the License is distributed on an "AS IS" BASIS,
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+package org.apache.arrow.vector.complex.impl;
+
+import org.apache.arrow.vector.ExtensionTypeVector;
+
+public interface ExtensionTypeWriterFactory<T extends AbstractFieldWriter> {
```
Comment (lidavidm) [inline vector/src/main/java/org/apache/arrow/vector/complex/impl/ExtensionTypeWriterFactory.java:21]: Can we document this?

Comment (lidavidm) [reply vector/src/main/java/org/apache/arrow/vector/complex/impl/ExtensionTypeWriterFactory.java:21]: Does the type bound need to be `AbstractFieldWriter` or can it just be `FieldWriter` (the interface)?

File: vector/src/main/java/org/apache/arrow/vector/holders/ExtensionHolder.java [hunk 2]
```diff
@@ -0,0 +1,21 @@
...
+ *
+ * Unless required by applicable law or agreed to in writing, software
+ * distributed under the License is distributed on an "AS IS" BASIS,
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+package org.apache.arrow.vector.holders;
+
+public abstract class ExtensionHolder implements ValueHolder {
```
Comment (lidavidm) [inline vector/src/main/java/org/apache/arrow/vector/holders/ExtensionHolder.java:19]: Can we document this?

File: vector/src/test/java/org/apache/arrow/vector/complex/impl/TestPromotableWriter.java [hunk 3]
```diff
@@ -776,4 +780,95 @@ public void testPromoteToUnionFromDecimal() throws Exception {
...
+  }
+
+  public class UuidWriterImpl extends AbstractFieldWriter {
+    private final UuidVector vector;
+
+    public UuidWriterImpl(UuidVector vector) {
+      this.vector = vector;
+    }
+
+    @Override
```
Comment (lidavidm) [inline vector/src/test/java/org/apache/arrow/vector/complex/impl/TestPromotableWriter.java:828]: Is there a way we can provide default implementations for these functions to reduce the boilerplate?

File: vector/src/test/java/org/apache/arrow/vector/types/pojo/TestExtensionType.java
Comment (lidavidm) [inline vector/src/test/java/org/apache/arrow/vector/types/pojo/TestExtensionType.java:1]: We may want to just pull the UuidType into a toplevel class now that it's being used by multiple tests.

**Review by lidavidm — COMMENTED** [review]
Can we preserve the original committer's information if possible so they can get the credit for the original work? (A `Co-authored-by` tag in the PR should suffice I think)

Is there some way we could have a type-safe design instead of just `Object` everywhere?

File: vector/src/main/java/org/apache/arrow/vector/complex/impl/ExtensionTypeWriterFactory.java (hunk 1 above)
Comment (xxlaykxx) [reply vector/src/main/java/org/apache/arrow/vector/complex/impl/ExtensionTypeWriterFactory.java:21]: I chose **AbstractFieldWriter** just to make sure that the user will use some specific implementation of writer, but in general yes - it could be FieldWriter

**Comment by xxlaykxx** [comment]
> Can we preserve the original committer's information if possible so they can get the credit for the original work? (A `Co-authored-by` tag in the PR should suffice I think)
> 
> Is there some way we could have a type-safe design instead of just `Object` everywhere?

Because the type is unknown, we could allow only Holder impl for writing. Is this acceptable?

File: vector/src/test/java/org/apache/arrow/vector/types/pojo/TestUuidVector.java [hunk 4]
```diff
@@ -0,0 +1,152 @@
...
+import org.apache.arrow.vector.FieldVector;
+import org.apache.arrow.vector.FixedSizeBinaryVector;
+import org.apache.arrow.vector.ValueIterableVector;
+import org.apache.arrow.vector.ValueVector;
+import org.apache.arrow.vector.types.pojo.ArrowType.ExtensionType;
+import org.apache.arrow.vector.util.TransferPair;
+
+public class TestUuidVector {
+
+  public static class UuidType extends ExtensionType {
```
Comment (lidavidm) [inline vector/src/test/java/org/apache/arrow/vector/types/pojo/TestUuidVector.java:33]: What I meant was, can we just make this a toplevel class? Not a nested class?

File: vector/src/test/java/org/apache/arrow/vector/types/pojo/TestUuidVector.java [hunk 5]
```diff
@@ -0,0 +1,152 @@
...
+      return "";
+    }
+
+    @Override
+    public FieldVector getNewVector(String name, FieldType fieldType, BufferAllocator allocator) {
+      return new UuidVector(name, allocator, new FixedSizeBinaryVector(name, allocator, 16));
+    }
+  }
+
+  public static class UuidVector extends ExtensionTypeVector<FixedSizeBinaryVector>
```
Comment (lidavidm) [inline vector/src/test/java/org/apache/arrow/vector/types/pojo/TestUuidVector.java:70]: Same here

File: vector/src/test/java/org/apache/arrow/vector/types/pojo/TestUuidVector.java [hunk 6]
```diff
@@ -0,0 +1,152 @@
...
+import org.apache.arrow.memory.util.hash.ArrowBufHasher;
+import org.apache.arrow.vector.ExtensionTypeVector;
+import org.apache.arrow.vector.FieldVector;
+import org.apache.arrow.vector.FixedSizeBinaryVector;
+import org.apache.arrow.vector.ValueIterableVector;
+import org.apache.arrow.vector.ValueVector;
+import org.apache.arrow.vector.types.pojo.ArrowType.ExtensionType;
+import org.apache.arrow.vector.util.TransferPair;
+
+public class TestUuidVector {
```
Comment (lidavidm) [inline vector/src/test/java/org/apache/arrow/vector/types/pojo/TestUuidVector.java:31]: In fact why is this class here at all? All it does is wrap the two inner classes

File: vector/src/main/codegen/templates/BaseWriter.java [hunk 7]
```diff
@@ -101,6 +103,13 @@ public interface MapWriter extends ListWriter {
     MapWriter value();
   }
 
+  public interface ExtensionWriter extends BaseWriter {
+    void writeNull();
+    <T extends ExtensionHolder> void write(T var1);
+    void writeExtensionType(Object var1);
+    <T extends ExtensionTypeWriterFactory> void addExtensionTypeFactory(T var1);
```
Comment (lidavidm) [inline vector/src/main/codegen/templates/BaseWriter.java:110]: While the existing code is short on docstrings, can we add docstrings for new code going forward? In particular it's not clear what `addExtensionTypeFactory` is or how to use it

Comment (lidavidm) [reply vector/src/main/codegen/templates/BaseWriter.java:110]: Are the generic bounds actually useful here? Why can't it just be `ExtensionTypeWriterFactory var1`?

Comment (lidavidm) [reply vector/src/main/codegen/templates/BaseWriter.java:110]: Can we replace `var1` with meaningful parameter names?

File: vector/src/main/codegen/templates/BaseWriter.java [hunk 8]
```diff
@@ -101,6 +103,13 @@ public interface MapWriter extends ListWriter {
     MapWriter value();
   }
 
+  public interface ExtensionWriter extends BaseWriter {
+    void writeNull();
+    <T extends ExtensionHolder> void write(T var1);
```
Comment (lidavidm) [inline vector/src/main/codegen/templates/BaseWriter.java:108]: Same here - why not just `void write(ExtensionHolder value)`?

File: vector/src/main/java/org/apache/arrow/vector/complex/impl/ExtensionTypeWriterFactory.java (hunk 1 above)
Comment (lidavidm) [reply vector/src/main/java/org/apache/arrow/vector/complex/impl/ExtensionTypeWriterFactory.java:27]: IMO abstract implementation classes should not go in generic bounds - it should be the interface type

File: vector/src/main/java/org/apache/arrow/vector/complex/impl/ExtensionTypeWriterFactory.java [hunk 9]
```diff
@@ -0,0 +1,29 @@
...
+import org.apache.arrow.vector.ExtensionTypeVector;
+
+/**
+ * A factory for {@link ExtensionTypeWriter} instances. The factory allow to configure writer
+ * implementation for specific ExtensionTypeVector.
+ *
+ * @param <T> writer implementation for specific {@link ExtensionTypeVector}.
+ */
+public interface ExtensionTypeWriterFactory<T extends AbstractFieldWriter> {
+  T getWriterImpl(ExtensionTypeVector vector);
```
Comment (lidavidm) [inline vector/src/main/java/org/apache/arrow/vector/complex/impl/ExtensionTypeWriterFactory.java:28]: Can we document the methods as well?

File: vector/src/test/java/org/apache/arrow/vector/complex/impl/TestPromotableWriter.java
Comment (lidavidm) [inline vector/src/test/java/org/apache/arrow/vector/complex/impl/TestPromotableWriter.java:1]: I don't see any test of using ExtensionHolder?

File: vector/src/main/codegen/templates/BaseWriter.java (hunk 8 above)
Comment (xxlaykxx) [reply vector/src/main/codegen/templates/BaseWriter.java]: fixed

File: vector/src/main/codegen/templates/BaseWriter.java [hunk 10]
```diff
@@ -101,6 +103,35 @@ public interface MapWriter extends ListWriter {
...
 
+  public interface ExtensionWriter extends BaseWriter {
+    
+    /**
+     * Writes a null value.
+     */
+    void writeNull();
+
+    /**
+     * Writes vlaue from the given extension holder.
```
Comment (lidavidm) [inline vector/src/main/codegen/templates/BaseWriter.java:114]:
```suggestion
     * Writes value from the given extension holder.
```

File: vector/src/test/java/org/apache/arrow/vector/complex/impl/UuidWriterImpl.java [hunk 11]
```diff
@@ -0,0 +1,49 @@
...
+    ByteBuffer bb = ByteBuffer.allocate(16);
+    bb.putLong(uuid.getMostSignificantBits());
+    bb.putLong(uuid.getLeastSignificantBits());
+    ((UuidVector) this.vector).setSafe(this.idx(), bb.array());
+    this.vector.setValueCount(this.idx() + 1);
+  }
+
+  @Override
+  public void write(ExtensionHolder holder) {
+    if (holder instanceof UuidHolder) {
```
Comment (lidavidm) [inline vector/src/test/java/org/apache/arrow/vector/complex/impl/UuidWriterImpl.java:43]: Either delete the check to be consistent with writeExtensionType or explicitly error if the holder is the wrong type

File: vector/src/test/java/org/apache/arrow/vector/complex/impl/UuidWriterImpl.java [hunk 12]
```diff
@@ -0,0 +1,49 @@
...
+ */
+package org.apache.arrow.vector.complex.impl;
+
+import java.nio.ByteBuffer;
+import java.util.UUID;
+import org.apache.arrow.vector.UuidVector;
+import org.apache.arrow.vector.holder.UuidHolder;
+import org.apache.arrow.vector.holders.ExtensionHolder;
+
+public class UuidWriterImpl extends AbstractExtensionTypeWriter {
```
Comment (lidavidm) [inline vector/src/test/java/org/apache/arrow/vector/complex/impl/UuidWriterImpl.java:25]:
```suggestion
public class UuidWriterImpl extends AbstractExtensionTypeWriter<UuidVector> {
```

File: vector/src/test/java/org/apache/arrow/vector/complex/impl/UuidWriterImpl.java [hunk 13]
```diff
@@ -0,0 +1,49 @@
...
+    super(vector);
+  }
+
+  @Override
+  public void writeExtensionType(Object value) {
+    UUID uuid = (UUID) value;
+    ByteBuffer bb = ByteBuffer.allocate(16);
+    bb.putLong(uuid.getMostSignificantBits());
+    bb.putLong(uuid.getLeastSignificantBits());
+    ((UuidVector) this.vector).setSafe(this.idx(), bb.array());
```
Comment (lidavidm) [inline vector/src/test/java/org/apache/arrow/vector/complex/impl/UuidWriterImpl.java:37]:
```suggestion
    vector.setSafe(idx(), bb.array());
```

File: vector/src/test/java/org/apache/arrow/vector/complex/impl/UuidWriterImpl.java [hunk 14]
```diff
@@ -0,0 +1,49 @@
...
+    this.vector.setValueCount(this.idx() + 1);
+  }
+
+  @Override
+  public void write(ExtensionHolder holder) {
+    if (holder instanceof UuidHolder) {
+      UuidHolder uuidHolder = (UuidHolder) holder;
+      ((UuidVector) this.vector).setSafe(this.idx(), uuidHolder.value);
+      this.vector.setValueCount(this.idx() + 1);
```
Comment (lidavidm) [inline vector/src/test/java/org/apache/arrow/vector/complex/impl/UuidWriterImpl.java:46]:
```suggestion
      vector.setSafe(idx(), uuidHolder.value);
      vector.setValueCount(idx() + 1);
```

File: vector/src/main/codegen/templates/BaseWriter.java [hunk 15]
```diff
@@ -101,6 +103,35 @@ public interface MapWriter extends ListWriter {
...
+     * @param holder the extension holder to write
+     */
+    void write(ExtensionHolder holder);
+
+    /**
+     * Writes the given extension type value.
+     *
+     * @param value the extension type value to write
+     */
+    void writeExtensionType(Object value);
```
Comment (lidavidm) [inline vector/src/main/codegen/templates/BaseWriter.java:125]: This is a nit but now I'm thinking it should be just `writeExtension` to parallel `writeVarChar`

File: vector/src/main/codegen/templates/BaseWriter.java [hunk 16]
```diff
@@ -101,6 +103,35 @@ public interface MapWriter extends ListWriter {
...
+    
+    /**
+     * Adds the given extension type factory. This factory allows configuring writer implementations for specific ExtensionTypeVector.
+     *
+     * @param factory the extension type factory to add
+     */
+    void addExtensionTypeFactory(ExtensionTypeWriterFactory factory);
```
Comment (lidavidm) [inline vector/src/main/codegen/templates/BaseWriter.java:132]:
```suggestion
    void addExtensionTypeWriterFactory(ExtensionTypeWriterFactory factory);
```
for consistency as well

File: vector/src/main/java/org/apache/arrow/vector/complex/impl/AbstractExtensionTypeWriter.java [hunk 17]
```diff
@@ -0,0 +1,71 @@
...
+  }
+
+  @Override
+  public void clear() {
+    this.vector.clear();
+  }
+
+  @Override
+  protected int idx() {
+    return super.idx();
```
Comment (lidavidm) [inline vector/src/main/java/org/apache/arrow/vector/complex/impl/AbstractExtensionTypeWriter.java:63]: Hmm, is the only reason we override here to make it `protected` instead of package-private? (Should we just use `getPosition()` instead as it is already public and does the same thing?)

**Review by lidavidm — COMMENTED** [review]
Looking good, just some final naming questions

File: vector/src/main/java/org/apache/arrow/vector/complex/impl/AbstractExtensionTypeWriter.java (hunk 17 above)
Comment (xxlaykxx) [reply vector/src/main/java/org/apache/arrow/vector/complex/impl/AbstractExtensionTypeWriter.java:63]: yep, makes sense - logic with idx() method added for all other writers.

**Review by lidavidm — COMMENTED** [review]
LGTM, but please see the pre-commit failures

**Comment by lidavidm** [comment]
Thanks @xxlaykxx @FiV0!
