### PR TITLE
GH-343: Fix ListVector offset buffer not properly serialized for nested empty arrays

### LINKED ISSUE #343: [C++/Java] Error when reading inner lists within a struct in empty outer lists from C++/Python in Java
When using C++ (or Python) to construct a null or empty outer array of type **array_1: list<item: struct<array_sub_col: list<item: string>>>**, either:
```

-  array_1: null
-  array_1: []
```

an out of bounds exceptions (see stack trace below) follows when later retrieving the field reader for the inner list (**array_sub_col**) in Java, when trying to access the subsequent offset buffer: https://github.com/apache/arrow/blob/master/java/vector/src/main/java/org/apache/arrow/vector/complex/impl/UnionListReader.java#L64
## Reproduction

**Java**: 7.0.0
**C++**: 7.0.0
**Python**: 7.0.0

Creating a stream on C++ of type **array_1: list<item: struct<array_sub_col: list<item: string>>>** with an empty (or null) outer list:
```c++
arrow::MemoryPool* pool = arrow::default_memory_pool();
arrow::Result<std::shared_ptr<arrow::io::BufferOutputStream>> stream_buffer =
    arrow::io::BufferOutputStream::Create(1, pool);

std::vector<std::shared_ptr<arrow::Field>> inner_list_field{std::make_shared<arrow::Field>("array_sub_col", arrow::list(arrow::utf8()))};

// Datatype for the builder: list<struct<list<string>>>
std::shared_ptr<DataType> data_type = list(struct_(inner_list_field));

std::unique_ptr<arrow::ArrayBuilder> builder;
arrow::MakeBuilder(pool, data_type, &builder);
auto* list_builder = dynamic_cast<arrow::ListBuilder*>(builder.get());

// Append a null or an empty list to the outer list
list_builder->AppendNull(); // or list_builder->AppendEmptyValue()

std::vector<std::shared_ptr<arrow::Array>> value_batch;
value_batch.resize(1);
list_builder->Finish(&value_batch[0]);

std::vector<std::shared_ptr<arrow::Field>> outer_list_field{std::make_shared<arrow::Field>("array_1",data_type)};
auto schema = std::make_shared<arrow::Schema>(outer_list_field);

// Build a single row record batch
std::shared_ptr<arrow::RecordBatch> batch = RecordBatch::Make(schema, 1, value_batch);
ASSERT_OK(batch->Validate());

// Stream the batch to a file to later read on the Java side
arrow::Result<std::shared_ptr<ipc::RecordBatchWriter>> stream_writer = 
    arrow::ipc::MakeStreamWriter(stream_buffer.ValueOrDie().get(), schema, arrow::ipc::IpcWriteOptions::Defaults());
stream_writer.ValueOrDie()->WriteRecordBatch(*batch);

arrow::Result<std::shared_ptr<arrow::Buffer>> buffer_result = stream_buffer.ValueOrDie()->Finish();
std::shared_ptr<arrow::Buffer> buffer = buffer_result.ValueOrDie();
auto file_output = arrow::io::FileOutputStream::Open("/tmp/batch_stream.out").ValueOrDie();
file_output->Write(buffer->data(), buffer->size());
file_output->Close();
```
As expected, Python holds the same memory layout for the field vectors as the C++ code above:
```python
array = pa.array([None], type=pa.list_(pa.struct([pa.field("array_sub_col", pa.list_(pa.utf8()))])))
batch = pa.record_batch([struct_array], names=["array_1"])

sink = pa.BufferOutputStream()
with pa.ipc.new_stream(sink, batch.schema) as writer:
    writer.write_batch(batch)
buf = sink.getvalue()

with open('/tmp/batch_stream.out', 'wb') as f:
    f.write(buf)
```
**Java fails when then trying to access the inner list's field reader:**
```java
File file = new File("/tmp/batch_stream.out");
byte[] bytes = FileUtils.readFileToByteArray(file);
try (ArrowStreamReader reader = new ArrowStreamReader(new ByteArrayInputStream(bytes), allocator)) {
     Schema schema = reader.getVectorSchemaRoot().getSchema();
     reader.loadNextBatch();
     readBatch.getVector("array_1").getReader().reader().reader("array_sub_col");                     // <- fails: reader("array_sub_col") fails with OOB

     // Concrete readers:
     // FieldVector array_1 = readBatch.getVector("array_1");
     // UnionListReader array_1_reader = (UnionListReader) array_1.getReader();
     // NullableStructReaderImpl struct_reader = (NullableStructReaderImpl) array_1_reader.reader();
     // FieldReader union_list_reader = struct_reader.reader("array_sub_col");                        // <- fails: OOB
```
### Stack trace:
```

java.lang.reflect.InvocationTargetException
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:297)
    at java.lang.Thread.run (Thread.java:829)
Caused by: java.lang.IndexOutOfBoundsException: index: 4, length: 4 (expected: range(0, 4))
    at org.apache.arrow.memory.ArrowBuf.checkIndexD (ArrowBuf.java:318)
    at org.apache.arrow.memory.ArrowBuf.chk (ArrowBuf.java:305)
    at org.apache.arrow.memory.ArrowBuf.getInt (ArrowBuf.java:424)
    at com.test.arrow.ValidateArrow.testArrow (ValidateArrow.java:433)
    at com.test.arrow.ValidateArrow.main (ValidateArrow.java:440)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:297)
    at java.lang.Thread.run (Thread.java:829)
```

**Reporter**: [Arrow User](https://issues.apache.org/jira/browse/ARROW-15971)

<sub>**Note**: *This issue was originally created as [ARROW-15971](https://issues.apache.org/jira/browse/ARROW-15971). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

### PR DESCRIPTION
**Pull request by Yicong-Huang**
## What's Changed

Fix `ListVector`/`LargeListVector` IPC serialization when `valueCount` is 0.

### Problem

When `valueCount == 0`, `setReaderAndWriterIndex()` was setting `offsetBuffer.writerIndex(0)`, which means `readableBytes() == 0`. IPC serializer uses `readableBytes()` to determine buffer size, so 0 bytes were written to the IPC stream. This crashes IPC readers in other libraries because Arrow spec requires offset buffer to have at least one entry `[0]`.

@viirya:

> The offset buffers are allocated properly. But during IPC serialization, they are ignored.
> ```
>   public long readableBytes() {
>       return writerIndex - readerIndex;
>   }
> ```
> So when ListVector.setReaderAndWriterIndex() sets writerIndex(0) and readerIndex(0), readableBytes() returns 0 - 0 = 0.
> 
> Then when MessageSerializer.writeBatchBuffers() calls WriteChannel.write(buffer), it writes 0 bytes.
>
> So the flow is:
> 
> valueCount=0 → ListVector.setReaderAndWriterIndex() sets offsetBuffer.writerIndex(0)
> VectorUnloader.getFieldBuffers() returns the buffer with writerIndex=0
> MessageSerializer.writeBatchBuffers() writes the buffer
> WriteChannel.write(buffer) checks buffer.readableBytes() which is 0
> 0 bytes are written to the IPC stream
> PyArrow read the batch with the missing buffer → crash when other libraries to read

### Fix

Simplify `setReaderAndWriterIndex()` to always use `(valueCount + 1) * OFFSET_WIDTH` for offset buffer's `writerIndex`. When `valueCount == 0`, this correctly sets `writerIndex` to `OFFSET_WIDTH`, ensuring `offset[0]` is included in serialization.

### Testing

Added tests for nested empty lists verifying offset buffer has correct `readableBytes()`.

Closes #343.

### CODE REVIEW

File: vector/src/main/java/org/apache/arrow/vector/complex/LargeListVector.java [hunk 1]
```diff
@@ -309,7 +320,8 @@ private void setReaderAndWriterIndex() {
     offsetBuffer.readerIndex(0);
     if (valueCount == 0) {
       validityBuffer.writerIndex(0);
-      offsetBuffer.writerIndex(0);
+      // Even when valueCount is 0, offset buffer should have offset[0] per Arrow spec
```
Comment (viirya) [inline vector/src/main/java/org/apache/arrow/vector/complex/LargeListVector.java]: It is better to explain it clearly:
```suggestion
      // IPC serializer will determine readable bytes based on `readerIndex` and `writerIndex`.
      //  Both are set to 0 means 0 bytes are written to the IPC stream which will crash IPC readers
      // in other libraries. According to Arrow spec, we should still output the offset buffer which
      // is [0].
```

**Comment by viirya** [comment]
> When outer array is empty, nested writers are never invoked, so child list's offset buffer remains unallocated (capacity = 0). This violates Arrow spec which requires offset[0] = 0.

I think you are referring the writers in Spark. It is out of context here and not related to the root cause. We should update the description to explain the issue clearly.

The offset buffers are actually allocated properly. But during IPC serialization, they are ignored.

```Java
  public long readableBytes() {
      return writerIndex - readerIndex;
  }
```

So when ListVector.setReaderAndWriterIndex() sets writerIndex(0) and readerIndex(0), readableBytes() returns 0 - 0 = 0.

Then when MessageSerializer.writeBatchBuffers() calls WriteChannel.write(buffer), it writes 0 bytes.

So the flow is:
  1. valueCount=0 → ListVector.setReaderAndWriterIndex() sets offsetBuffer.writerIndex(0)
  2. VectorUnloader.getFieldBuffers() returns the buffer with writerIndex=0
  3. MessageSerializer.writeBatchBuffers() writes the buffer
  4. WriteChannel.write(buffer) checks buffer.readableBytes() which is 0
  5. 0 bytes are written to the IPC stream
  6. PyArrow read the batch with the missing buffer → crash when other libraries to read

**Comment by viirya** [comment]
Hi @lidavidm @jbonofre, do you think this can catch up the Arrow Java 19.0.0 release?

File: vector/src/main/java/org/apache/arrow/vector/complex/LargeListVector.java (hunk 1 above)
Comment (Yicong-Huang) [reply vector/src/main/java/org/apache/arrow/vector/complex/LargeListVector.java]: Thanks! changed to this comment.

File: vector/src/main/java/org/apache/arrow/vector/complex/ListVector.java [hunk 2]
```diff
@@ -236,7 +236,6 @@ public List<ArrowBuf> getFieldBuffers() {
     setReaderAndWriterIndex();
     result.add(validityBuffer);
     result.add(offsetBuffer);
-
```
Comment (viirya) [inline vector/src/main/java/org/apache/arrow/vector/complex/ListVector.java]: Please revert unnecessary change.

Comment (Yicong-Huang) [reply vector/src/main/java/org/apache/arrow/vector/complex/ListVector.java]: reverted. thanks!

File: vector/src/main/java/org/apache/arrow/vector/complex/LargeListVector.java [hunk 3]
```diff
@@ -307,13 +306,12 @@ public void exportCDataBuffers(List<ArrowBuf> buffers, ArrowBuf buffersPtr, long
...
     validityBuffer.readerIndex(0);
     offsetBuffer.readerIndex(0);
-    if (valueCount == 0) {
-      validityBuffer.writerIndex(0);
-      offsetBuffer.writerIndex(0);
-    } else {
-      validityBuffer.writerIndex(BitVectorHelper.getValidityBufferSizeFromCount(valueCount));
-      offsetBuffer.writerIndex((valueCount + 1) * OFFSET_WIDTH);
-    }
+    validityBuffer.writerIndex(BitVectorHelper.getValidityBufferSizeFromCount(valueCount));
```
[the remark this answers is not in the document]
Comment (viirya) [reply vector/src/main/java/org/apache/arrow/vector/complex/LargeListVector.java]: Oh, if `BitVectorHelper.getValidityBufferSizeFromCount(valueCount)` returns 0 for `valueCount == 0`, then it is okay.

File: vector/src/test/java/org/apache/arrow/vector/TestLargeListVector.java [hunk 4]
```diff
@@ -1100,6 +1100,38 @@ public void testCopyValueSafeForExtensionType() throws Exception {
...
+  @Test
+  public void testNestedEmptyLargeListOffsetBuffer() {
+    // Test that nested LargeListVector properly allocates offset buffer
+    // even when nested writers are never invoked. According to Arrow spec,
+    // offset buffer must have N+1 entries. Even when N=0, it should contain [0].
+    try (LargeListVector outerList = LargeListVector.empty("outer", allocator)) {
+      // Setup LargeList<LargeList<Int>>
+      outerList.addOrGetVector(FieldType.nullable(MinorType.LARGELIST.getType()));
+      LargeListVector innerList = (LargeListVector) outerList.getDataVector();
+      innerList.addOrGetVector(FieldType.nullable(MinorType.INT.getType()));
```
Comment (viirya) [inline vector/src/test/java/org/apache/arrow/vector/TestLargeListVector.java]: I looked these tests again. I think this nested structure is not necessary for the unit tests here. It only matter for our usage at Spark side (on the ArrowWriters). But for here, we just need to make sure that a ListVector/LargeListVector has meaningful and correct `readableBytes` value after they are allocated.

Maybe we can simplify these tests.

**Review by viirya — COMMENTED** [review]
I only have some comments on the tests to simplify them. Otherwise, the fix looks correct to me.

@jbonofre @lidavidm Can you take a look and see if we can get this into the next release?

Thank you!

**Review by jbonofre — APPROVED** [review]
LGTM, thanks !

**Review by viirya — COMMENTED** [review]
@Yicong-Huang Should we also fix setReaderAndWriterIndex at BaseVariableWidthVector?

**Comment by viirya** [comment]
> > @viirya ok, I understand. Let me complete 19.0.0 first, I will prepare 18.3.1 after.
> 
> Thank you so much! @jbonofre

Hello @jbonofre, thank you for reviewing and preparing 19.0.0 release. Now as 19.0.0 was released, can you help us prepare 18.3.1 release including these fixes if you have time? Thank you!

**Comment by dmitry-chirkov-dremio** [comment]
We are troubleshooting a regression that ends up in following stack:

```
(java.lang.IndexOutOfBoundsException) readerIndex: 0, writerIndex: 4 (expected: 0 <= readerIndex <= writerIndex <= capacity(0))
    io.netty.buffer.AbstractByteBuf.checkIndexBounds():112
    io.netty.buffer.AbstractByteBuf.writerIndex():135
    io.netty.buffer.NettyArrowBuf.writerIndex():215
    io.netty.buffer.NettyArrowBuf.unwrapBuffer():631
```
 
Our starting point is [this](https://github.com/dremio/dremio-oss/blob/799ccbda47e6f2e1bfacf1ccbded174e00d4150a/sabot/kernel/src/main/java/com/dremio/exec/record/FragmentWritableBatch.java#L110).

Is it possible that merged changes break Netty's assumptions in [unwrapBuffer](https://github.com/apache/arrow-java/blob/cb24576e895c0bf8e1d062e2fc82f2b53bfa2eb8/memory/memory-netty-buffer-patch/src/main/java/io/netty/buffer/NettyArrowBuf.java#L624)?

edit: looks like change in https://github.com/apache/arrow-java/pull/989 was more involved (and more correct?)
