### PR TITLE
GH-704: Fix initialization of offset buffer when exporting VarChar vectors through C Data Interface

### LINKED ISSUE #704: Offset buffer contains garbled data when exporting empty string arrays from Java
### Describe the bug, including details regarding any error messages, version, and platform.

https://github.com/apache/arrow/pull/40043 fixes exporting empty string arrays by exporting a non-empty offset buffer. However, the offset buffer is not properly initialized. The first byte of the offset buffer may not be 0 and causes weird errors on the importing side. See https://github.com/apache/datafusion-comet/issues/1615 for a issue of datafusion-comet caused by this.

This may also relates to https://github.com/apache/arrow-java/issues/88. https://github.com/apache/arrow/pull/40043 introduces a bug that corrupts the offset buffer before reading.

### PR DESCRIPTION
**Pull request by Kontinuation**
## What's Changed

This patch fixes the initialization of offset buffers when exporting variable width arrays through Arrow C Data Interface. The original code incorrectly mess up with the member `this.offsetBuffer` while we should actually initialize the newly allocated offsetBuffer. I think the diff itself will be quite self-explanatory.

Closes #704 and probably #88 .

### CODE REVIEW

File: c/src/test/java/org/apache/arrow/c/RoundtripTest.java [hunk 1]
```diff
@@ -77,6 +79,7 @@
 import org.apache.arrow.vector.ValueVector;
 import org.apache.arrow.vector.VarBinaryVector;
 import org.apache.arrow.vector.VarCharVector;
+import org.apache.arrow.vector.VariableWidthVector;
```
Comment (lidavidm) [inline c/src/test/java/org/apache/arrow/c/RoundtripTest.java:82]: Unintentional import? This is failing the build

**Review by lidavidm — APPROVED** [review]

File: c/src/test/java/org/apache/arrow/c/RoundtripTest.java (hunk 1 above)
Comment (Kontinuation) [reply c/src/test/java/org/apache/arrow/c/RoundtripTest.java]: Fixed. Other test failures seems to be unrelated to this PR.

**Review by lidavidm — APPROVED** [review]
